### ISSUE TITLE
Queries regarding OAM Agent

### ISSUE THREAD

**Issue by Prajesh-Dhungel** [open-ness/epcforedge#6]
Hi Team,

1.As we were running the unit test (command: ./ut_test all),we captured http messages in wireshark but we are unable to docode the packets as we dont know where the logs are and we dont have preshared key.

2. We have a query whether OAM agent supports communication with EPC, if it supports which files/APIs should we refer to understand the message flow between OAMAgent and EPC.We noticed in the documents that implementation is vendor specific and the diagram (Figure 6) says internal communication between EPC OAM Agent and EPC CPF.(Link to diagram:https://github.com/open-ness/specs/blob/master/doc/core-network/epc-images/openness_epcupf_add.png)

Any information would be highly appreciated.
Thank you

**Comment by MouliBurla** [comment]
Hi,

For the query #2, your understanding is correct. communication between OAM agent and EPC is an internal communication based on EPC vendor, as this interface is dectated by EPC solution provider.  In OpenNESS, this interface is stubbed and looped back in  OAM agent for the purpose of standalone testing (without EPC solution).   

Regards,

**Comment by tongtongxiaopeng1979** [comment]
> Hi Team,
> 
> 1.As we were running the unit test (command: ./ut_test all),we captured http messages in wireshark but we are unable to docode the packets as we dont know where the logs are and we dont have preshared key.
> 
> 1. We have a query whether OAM agent supports communication with EPC, if it supports which files/APIs should we refer to understand the message flow between OAMAgent and EPC.We noticed in the documents that implementation is vendor specific and the diagram (Figure 6) says internal communication between EPC OAM Agent and EPC CPF.(Link to diagram:https://github.com/open-ness/specs/blob/master/doc/core-network/epc-images/openness_epcupf_add.png)
> 
> Any information would be highly appreciated.
> Thank you

for #1,  you can look at

https://github.com/open-ness/epcforedge/blob/master/lte/backend/test/unit_test/scripts/ut-test

The key generation as below:

    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${CURRENT_DIR}/ssl/mec.key -out ${CURRENT_DIR}/ssl/mec.crt -subj "/C=US/ST=Mec/L=Mec/O=Mec/OU=Mec/CN=mec.local"
    cp -a ${CURRENT_DIR}/ssl ${NGINX_SSL}

BR
xiaopengt
