### ISSUE TITLE
Trailing spaces causing interpretation errors

### ISSUE THREAD

**Issue by huornlmj** [open-ness/epcforedge#7]
The following lines have a trailing space which are causing interpreter issues:

https://github.com/open-ness/epcforedge/blob/e0fecda4b313cc2a620f6ee4a4b515dc9b748b49/ngc/build/onprem/nef/Dockerfile#L16
https://github.com/open-ness/epcforedge/blob/e0fecda4b313cc2a620f6ee4a4b515dc9b748b49/ngc/build/onprem/af/Dockerfile#L16
https://github.com/open-ness/epcforedge/blob/e0fecda4b313cc2a620f6ee4a4b515dc9b748b49/ngc/build/onprem/oam/Dockerfile#L17
https://github.com/open-ness/epcforedge/blob/e0fecda4b313cc2a620f6ee4a4b515dc9b748b49/ngc/build/networkedge/nef/Dockerfile#L16
https://github.com/open-ness/epcforedge/blob/e0fecda4b313cc2a620f6ee4a4b515dc9b748b49/ngc/build/networkedge/af/Dockerfile#L16
https://github.com/open-ness/epcforedge/blob/e0fecda4b313cc2a620f6ee4a4b515dc9b748b49/ngc/build/networkedge/oam/Dockerfile#L17

**Comment by amr-mokhtar** [comment]
Hi @huornlmj, this issue has been addressed and the fix will become available in 20.09 release.
